//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 3 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var launchScreen: launchScreen { .init(source: .init(bundle: bundle, tableName: "LaunchScreen", preferredLanguages: preferredLanguages, locale: locale)) }
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }
    var main: main { .init(source: .init(bundle: bundle, tableName: "Main", preferredLanguages: preferredLanguages, locale: locale)) }

    func launchScreen(preferredLanguages: [String]) -> launchScreen {
      .init(source: .init(bundle: bundle, tableName: "LaunchScreen", preferredLanguages: preferredLanguages, locale: locale))
    }
    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }
    func main(preferredLanguages: [String]) -> main {
      .init(source: .init(bundle: bundle, tableName: "Main", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.launchScreen` struct is generated, and contains static references to 0 localization keys.
    struct launchScreen {
      let source: RswiftResources.StringResource.Source
    }

    /// This `_R.string.localizable` struct is generated, and contains static references to 45 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: BleMessager
      ///
      /// Key: CFBundleDisplayName
      ///
      /// Locales: en, zh-Hans
      var cfBundleDisplayName: RswiftResources.StringResource { .init(key: "CFBundleDisplayName", tableName: "Localizable", source: source, developmentValue: "BleMessager", comment: nil) }

      /// en translation: CBAdvertisementDataIsConnectable
      ///
      /// Key: central_adv_key_connectable
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_connectable: RswiftResources.StringResource { .init(key: "central_adv_key_connectable", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataIsConnectable", comment: nil) }

      /// en translation: CBAdvertisementDataLocalNameKey
      ///
      /// Key: central_adv_key_localName
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_localName: RswiftResources.StringResource { .init(key: "central_adv_key_localName", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataLocalNameKey", comment: nil) }

      /// en translation: CBAdvertisementDataManufacturerDataKey
      ///
      /// Key: central_adv_key_manufacturer
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_manufacturer: RswiftResources.StringResource { .init(key: "central_adv_key_manufacturer", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataManufacturerDataKey", comment: nil) }

      /// en translation: CBAdvertisementDataOverflowServiceUUIDsKey
      ///
      /// Key: central_adv_key_overflowUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_overflowUuid: RswiftResources.StringResource { .init(key: "central_adv_key_overflowUuid", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataOverflowServiceUUIDsKey", comment: nil) }

      /// en translation: CBAdvertisementDataServiceUUIDsKey
      ///
      /// Key: central_adv_key_serviceUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_serviceUuid: RswiftResources.StringResource { .init(key: "central_adv_key_serviceUuid", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataServiceUUIDsKey", comment: nil) }

      /// en translation: CBAdvertisementDataSolicitedServiceUUIDsKey
      ///
      /// Key: central_adv_key_solicitedUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_solicitedUuid: RswiftResources.StringResource { .init(key: "central_adv_key_solicitedUuid", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataSolicitedServiceUUIDsKey", comment: nil) }

      /// en translation: CBAdvertisementDataServiceDataKey
      ///
      /// Key: central_adv_key_specificService
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_specificService: RswiftResources.StringResource { .init(key: "central_adv_key_specificService", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataServiceDataKey", comment: nil) }

      /// en translation: CBAdvertisementDataTxPowerLevelKey
      ///
      /// Key: central_adv_key_txPower
      ///
      /// Locales: en, zh-Hans
      var central_adv_key_txPower: RswiftResources.StringResource { .init(key: "central_adv_key_txPower", tableName: "Localizable", source: source, developmentValue: "CBAdvertisementDataTxPowerLevelKey", comment: nil) }

      /// en translation: A Boolean value that indicates whether the advertising event type is connectable.
      ///
      /// Key: central_adv_subtitle_connectable
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_connectable: RswiftResources.StringResource { .init(key: "central_adv_subtitle_connectable", tableName: "Localizable", source: source, developmentValue: "A Boolean value that indicates whether the advertising event type is connectable.", comment: nil) }

      /// en translation: The local name of a peripheral.
      ///
      /// Key: central_adv_subtitle_localName
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_localName: RswiftResources.StringResource { .init(key: "central_adv_subtitle_localName", tableName: "Localizable", source: source, developmentValue: "The local name of a peripheral.", comment: nil) }

      /// en translation: The manufacturer data of a peripheral.
      ///
      /// Key: central_adv_subtitle_manufacturer
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_manufacturer: RswiftResources.StringResource { .init(key: "central_adv_subtitle_manufacturer", tableName: "Localizable", source: source, developmentValue: "The manufacturer data of a peripheral.", comment: nil) }

      /// en translation: An array of UUIDs found in the overflow area of the advertisement data.
      ///
      /// Key: central_adv_subtitle_overflowUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_overflowUuid: RswiftResources.StringResource { .init(key: "central_adv_subtitle_overflowUuid", tableName: "Localizable", source: source, developmentValue: "An array of UUIDs found in the overflow area of the advertisement data.", comment: nil) }

      /// en translation: An array of service UUIDs.
      ///
      /// Key: central_adv_subtitle_serviceUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_serviceUuid: RswiftResources.StringResource { .init(key: "central_adv_subtitle_serviceUuid", tableName: "Localizable", source: source, developmentValue: "An array of service UUIDs.", comment: nil) }

      /// en translation: An array of solicited service UUIDs.
      ///
      /// Key: central_adv_subtitle_solicitedUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_solicitedUuid: RswiftResources.StringResource { .init(key: "central_adv_subtitle_solicitedUuid", tableName: "Localizable", source: source, developmentValue: "An array of solicited service UUIDs.", comment: nil) }

      /// en translation: A dictionary that contains service-specific advertisement data.
      ///
      /// Key: central_adv_subtitle_specificService
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_specificService: RswiftResources.StringResource { .init(key: "central_adv_subtitle_specificService", tableName: "Localizable", source: source, developmentValue: "A dictionary that contains service-specific advertisement data.", comment: nil) }

      /// en translation: The transmit power of a peripheral.
      ///
      /// Key: central_adv_subtitle_txPower
      ///
      /// Locales: en, zh-Hans
      var central_adv_subtitle_txPower: RswiftResources.StringResource { .init(key: "central_adv_subtitle_txPower", tableName: "Localizable", source: source, developmentValue: "The transmit power of a peripheral.", comment: nil) }

      /// en translation: Connectable
      ///
      /// Key: central_adv_title_connectable
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_connectable: RswiftResources.StringResource { .init(key: "central_adv_title_connectable", tableName: "Localizable", source: source, developmentValue: "Connectable", comment: nil) }

      /// en translation: Local Name
      ///
      /// Key: central_adv_title_localName
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_localName: RswiftResources.StringResource { .init(key: "central_adv_title_localName", tableName: "Localizable", source: source, developmentValue: "Local Name", comment: nil) }

      /// en translation: Manufacturer
      ///
      /// Key: central_adv_title_manufacturer
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_manufacturer: RswiftResources.StringResource { .init(key: "central_adv_title_manufacturer", tableName: "Localizable", source: source, developmentValue: "Manufacturer", comment: nil) }

      /// en translation: Overflow Uuid
      ///
      /// Key: central_adv_title_overflowUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_overflowUuid: RswiftResources.StringResource { .init(key: "central_adv_title_overflowUuid", tableName: "Localizable", source: source, developmentValue: "Overflow Uuid", comment: nil) }

      /// en translation: Service Uuid
      ///
      /// Key: central_adv_title_serviceUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_serviceUuid: RswiftResources.StringResource { .init(key: "central_adv_title_serviceUuid", tableName: "Localizable", source: source, developmentValue: "Service Uuid", comment: nil) }

      /// en translation: Solicited Uuid
      ///
      /// Key: central_adv_title_solicitedUuid
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_solicitedUuid: RswiftResources.StringResource { .init(key: "central_adv_title_solicitedUuid", tableName: "Localizable", source: source, developmentValue: "Solicited Uuid", comment: nil) }

      /// en translation: Specific Service
      ///
      /// Key: central_adv_title_specificService
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_specificService: RswiftResources.StringResource { .init(key: "central_adv_title_specificService", tableName: "Localizable", source: source, developmentValue: "Specific Service", comment: nil) }

      /// en translation: Tx Power
      ///
      /// Key: central_adv_title_txPower
      ///
      /// Locales: en, zh-Hans
      var central_adv_title_txPower: RswiftResources.StringResource { .init(key: "central_adv_title_txPower", tableName: "Localizable", source: source, developmentValue: "Tx Power", comment: nil) }

      /// en translation: 广播
      ///
      /// Key: central_bar_adv
      ///
      /// Locales: en, zh-Hans
      var central_bar_adv: RswiftResources.StringResource { .init(key: "central_bar_adv", tableName: "Localizable", source: source, developmentValue: "广播", comment: nil) }

      /// en translation: 日志
      ///
      /// Key: central_bar_log
      ///
      /// Locales: en, zh-Hans
      var central_bar_log: RswiftResources.StringResource { .init(key: "central_bar_log", tableName: "Localizable", source: source, developmentValue: "日志", comment: nil) }

      /// en translation: 服务
      ///
      /// Key: central_bar_service
      ///
      /// Locales: en, zh-Hans
      var central_bar_service: RswiftResources.StringResource { .init(key: "central_bar_service", tableName: "Localizable", source: source, developmentValue: "服务", comment: nil) }

      /// en translation: 扫描中
      ///
      /// Key: central_ble_scan_doing
      ///
      /// Locales: en, zh-Hans
      var central_ble_scan_doing: RswiftResources.StringResource { .init(key: "central_ble_scan_doing", tableName: "Localizable", source: source, developmentValue: "扫描中", comment: nil) }

      /// en translation: 开始扫描
      ///
      /// Key: central_ble_scan_paused
      ///
      /// Locales: en, zh-Hans
      var central_ble_scan_paused: RswiftResources.StringResource { .init(key: "central_ble_scan_paused", tableName: "Localizable", source: source, developmentValue: "开始扫描", comment: nil) }

      /// en translation: RSSI
      ///
      /// Key: central_filter_RSSI
      ///
      /// Locales: en, zh-Hans
      var central_filter_RSSI: RswiftResources.StringResource { .init(key: "central_filter_RSSI", tableName: "Localizable", source: source, developmentValue: "RSSI", comment: nil) }

      /// en translation: 重置
      ///
      /// Key: central_filter_reset
      ///
      /// Locales: en, zh-Hans
      var central_filter_reset: RswiftResources.StringResource { .init(key: "central_filter_reset", tableName: "Localizable", source: source, developmentValue: "重置", comment: nil) }

      /// en translation: 确认
      ///
      /// Key: central_filter_sure
      ///
      /// Locales: en, zh-Hans
      var central_filter_sure: RswiftResources.StringResource { .init(key: "central_filter_sure", tableName: "Localizable", source: source, developmentValue: "确认", comment: nil) }

      /// en translation: 过滤
      ///
      /// Key: central_filter_title
      ///
      /// Locales: en, zh-Hans
      var central_filter_title: RswiftResources.StringResource { .init(key: "central_filter_title", tableName: "Localizable", source: source, developmentValue: "过滤", comment: nil) }

      /// en translation: UUID
      ///
      /// Key: central_filter_uuid
      ///
      /// Locales: en, zh-Hans
      var central_filter_uuid: RswiftResources.StringResource { .init(key: "central_filter_uuid", tableName: "Localizable", source: source, developmentValue: "UUID", comment: nil) }

      /// en translation: 请输入UUID
      ///
      /// Key: central_filter_uuid_ph
      ///
      /// Locales: en, zh-Hans
      var central_filter_uuid_ph: RswiftResources.StringResource { .init(key: "central_filter_uuid_ph", tableName: "Localizable", source: source, developmentValue: "请输入UUID", comment: nil) }

      /// en translation: 请输入设备名称
      ///
      /// Key: central_search_ph
      ///
      /// Locales: en, zh-Hans
      var central_search_ph: RswiftResources.StringResource { .init(key: "central_search_ph", tableName: "Localizable", source: source, developmentValue: "请输入设备名称", comment: nil) }

      /// en translation: RSSI
      ///
      /// Key: central_sort_RSSI
      ///
      /// Locales: en, zh-Hans
      var central_sort_RSSI: RswiftResources.StringResource { .init(key: "central_sort_RSSI", tableName: "Localizable", source: source, developmentValue: "RSSI", comment: nil) }

      /// en translation: 名称
      ///
      /// Key: central_sort_name
      ///
      /// Locales: en, zh-Hans
      var central_sort_name: RswiftResources.StringResource { .init(key: "central_sort_name", tableName: "Localizable", source: source, developmentValue: "名称", comment: nil) }

      /// en translation: 手机作为中央设备来扫描和连接周围的蓝牙外设
      ///
      /// Key: entrance_opt_central_subtitle
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_central_subtitle: RswiftResources.StringResource { .init(key: "entrance_opt_central_subtitle", tableName: "Localizable", source: source, developmentValue: "手机作为中央设备来扫描和连接周围的蓝牙外设", comment: nil) }

      /// en translation: 中心模式
      ///
      /// Key: entrance_opt_central_title
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_central_title: RswiftResources.StringResource { .init(key: "entrance_opt_central_title", tableName: "Localizable", source: source, developmentValue: "中心模式", comment: nil) }

      /// en translation: 手机作为外围设备广播数据
      ///
      /// Key: entrance_opt_peripheral_subtitle
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_peripheral_subtitle: RswiftResources.StringResource { .init(key: "entrance_opt_peripheral_subtitle", tableName: "Localizable", source: source, developmentValue: "手机作为外围设备广播数据", comment: nil) }

      /// en translation: 外设模式
      ///
      /// Key: entrance_opt_peripheral_title
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_peripheral_title: RswiftResources.StringResource { .init(key: "entrance_opt_peripheral_title", tableName: "Localizable", source: source, developmentValue: "外设模式", comment: nil) }

      /// en translation: BleMessager
      ///
      /// Key: name
      ///
      /// Locales: en, zh-Hans
      var name: RswiftResources.StringResource { .init(key: "name", tableName: "Localizable", source: source, developmentValue: "BleMessager", comment: nil) }

      /// en translation: 蓝牙通信，畅享每一刻。
      ///
      /// Key: slogen
      ///
      /// Locales: en, zh-Hans
      var slogen: RswiftResources.StringResource { .init(key: "slogen", tableName: "Localizable", source: source, developmentValue: "蓝牙通信，畅享每一刻。", comment: nil) }
    }

    /// This `_R.string.main` struct is generated, and contains static references to 0 localization keys.
    struct main {
      let source: RswiftResources.StringResource.Source
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 23 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `auxiliary`.
    var auxiliary: RswiftResources.ColorResource { .init(name: "auxiliary", path: [], bundle: bundle) }

    /// Color `background`.
    var background: RswiftResources.ColorResource { .init(name: "background", path: [], bundle: bundle) }

    /// Color `balckAlways`.
    var balckAlways: RswiftResources.ColorResource { .init(name: "balckAlways", path: [], bundle: bundle) }

    /// Color `black`.
    var black: RswiftResources.ColorResource { .init(name: "black", path: [], bundle: bundle) }

    /// Color `content`.
    var content: RswiftResources.ColorResource { .init(name: "content", path: [], bundle: bundle) }

    /// Color `darkGray`.
    var darkGray: RswiftResources.ColorResource { .init(name: "darkGray", path: [], bundle: bundle) }

    /// Color `detail`.
    var detail: RswiftResources.ColorResource { .init(name: "detail", path: [], bundle: bundle) }

    /// Color `disabled`.
    var disabled: RswiftResources.ColorResource { .init(name: "disabled", path: [], bundle: bundle) }

    /// Color `divider`.
    var divider: RswiftResources.ColorResource { .init(name: "divider", path: [], bundle: bundle) }

    /// Color `error`.
    var error: RswiftResources.ColorResource { .init(name: "error", path: [], bundle: bundle) }

    /// Color `gray`.
    var gray: RswiftResources.ColorResource { .init(name: "gray", path: [], bundle: bundle) }

    /// Color `highlight`.
    var highlight: RswiftResources.ColorResource { .init(name: "highlight", path: [], bundle: bundle) }

    /// Color `lightGray`.
    var lightGray: RswiftResources.ColorResource { .init(name: "lightGray", path: [], bundle: bundle) }

    /// Color `link`.
    var link: RswiftResources.ColorResource { .init(name: "link", path: [], bundle: bundle) }

    /// Color `placeholder`.
    var placeholder: RswiftResources.ColorResource { .init(name: "placeholder", path: [], bundle: bundle) }

    /// Color `subtitle`.
    var subtitle: RswiftResources.ColorResource { .init(name: "subtitle", path: [], bundle: bundle) }

    /// Color `success`.
    var success: RswiftResources.ColorResource { .init(name: "success", path: [], bundle: bundle) }

    /// Color `theme`.
    var theme: RswiftResources.ColorResource { .init(name: "theme", path: [], bundle: bundle) }

    /// Color `title`.
    var title: RswiftResources.ColorResource { .init(name: "title", path: [], bundle: bundle) }

    /// Color `warning`.
    var warning: RswiftResources.ColorResource { .init(name: "warning", path: [], bundle: bundle) }

    /// Color `white`.
    var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }

    /// Color `whiteAlways`.
    var whiteAlways: RswiftResources.ColorResource { .init(name: "whiteAlways", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 3 images, and 8 namespaces.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `back`.
    var back: RswiftResources.ImageResource { .init(name: "back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `close`.
    var close: RswiftResources.ImageResource { .init(name: "close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logo`.
    var logo: RswiftResources.ImageResource { .init(name: "logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    var adv: adv { .init(bundle: bundle) }
    var arrow: arrow { .init(bundle: bundle) }
    var bar: bar { .init(bundle: bundle) }
    var ble: ble { .init(bundle: bundle) }
    var com: com { .init(bundle: bundle) }
    var doc: doc { .init(bundle: bundle) }
    var hud: hud { .init(bundle: bundle) }
    var triangle: triangle { .init(bundle: bundle) }

    func adv(bundle: Foundation.Bundle) -> adv {
      .init(bundle: bundle)
    }
    func arrow(bundle: Foundation.Bundle) -> arrow {
      .init(bundle: bundle)
    }
    func bar(bundle: Foundation.Bundle) -> bar {
      .init(bundle: bundle)
    }
    func ble(bundle: Foundation.Bundle) -> ble {
      .init(bundle: bundle)
    }
    func com(bundle: Foundation.Bundle) -> com {
      .init(bundle: bundle)
    }
    func doc(bundle: Foundation.Bundle) -> doc {
      .init(bundle: bundle)
    }
    func hud(bundle: Foundation.Bundle) -> hud {
      .init(bundle: bundle)
    }
    func triangle(bundle: Foundation.Bundle) -> triangle {
      .init(bundle: bundle)
    }


    /// This `_R.image.adv` struct is generated, and contains static references to 6 advs.
    struct adv {
      let bundle: Foundation.Bundle

      /// Image `adv/connectable`.
      var connectable: RswiftResources.ImageResource { .init(name: "adv/connectable", path: ["adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `adv/localName`.
      var localName: RswiftResources.ImageResource { .init(name: "adv/localName", path: ["adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `adv/manufacturer`.
      var manufacturer: RswiftResources.ImageResource { .init(name: "adv/manufacturer", path: ["adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `adv/power`.
      var power: RswiftResources.ImageResource { .init(name: "adv/power", path: ["adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `adv/service`.
      var service: RswiftResources.ImageResource { .init(name: "adv/service", path: ["adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `adv/uuid`.
      var uuid: RswiftResources.ImageResource { .init(name: "adv/uuid", path: ["adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }

    /// This `_R.image.arrow` struct is generated, and contains static references to 4 arrows.
    struct arrow {
      let bundle: Foundation.Bundle

      /// Image `arrow/bottom`.
      var bottom: RswiftResources.ImageResource { .init(name: "arrow/bottom", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `arrow/left`.
      var left: RswiftResources.ImageResource { .init(name: "arrow/left", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `arrow/right`.
      var right: RswiftResources.ImageResource { .init(name: "arrow/right", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `arrow/top`.
      var top: RswiftResources.ImageResource { .init(name: "arrow/top", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }

    /// This `_R.image.bar` struct is generated, and contains static references to 0 bars, and 3 namespaces.
    struct bar {
      let bundle: Foundation.Bundle
      var adv: adv { .init(bundle: bundle) }
      var log: log { .init(bundle: bundle) }
      var service: service { .init(bundle: bundle) }

      func adv(bundle: Foundation.Bundle) -> adv {
        .init(bundle: bundle)
      }
      func log(bundle: Foundation.Bundle) -> log {
        .init(bundle: bundle)
      }
      func service(bundle: Foundation.Bundle) -> service {
        .init(bundle: bundle)
      }


      /// This `_R.image.bar.adv` struct is generated, and contains static references to 2 advs.
      struct adv {
        let bundle: Foundation.Bundle

        /// Image `bar/adv/nor`.
        var nor: RswiftResources.ImageResource { .init(name: "bar/adv/nor", path: ["bar", "adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `bar/adv/sel`.
        var sel: RswiftResources.ImageResource { .init(name: "bar/adv/sel", path: ["bar", "adv"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.bar.log` struct is generated, and contains static references to 2 logs.
      struct log {
        let bundle: Foundation.Bundle

        /// Image `bar/log/nor`.
        var nor: RswiftResources.ImageResource { .init(name: "bar/log/nor", path: ["bar", "log"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `bar/log/sel`.
        var sel: RswiftResources.ImageResource { .init(name: "bar/log/sel", path: ["bar", "log"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.bar.service` struct is generated, and contains static references to 2 services.
      struct service {
        let bundle: Foundation.Bundle

        /// Image `bar/service/nor`.
        var nor: RswiftResources.ImageResource { .init(name: "bar/service/nor", path: ["bar", "service"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `bar/service/sel`.
        var sel: RswiftResources.ImageResource { .init(name: "bar/service/sel", path: ["bar", "service"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }
    }

    /// This `_R.image.ble` struct is generated, and contains static references to 0 bles, and 1 namespaces.
    struct ble {
      let bundle: Foundation.Bundle
      var scan: scan { .init(bundle: bundle) }

      func scan(bundle: Foundation.Bundle) -> scan {
        .init(bundle: bundle)
      }


      /// This `_R.image.ble.scan` struct is generated, and contains static references to 2 scans.
      struct scan {
        let bundle: Foundation.Bundle

        /// Image `ble/scan/nor`.
        var nor: RswiftResources.ImageResource { .init(name: "ble/scan/nor", path: ["ble", "scan"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `ble/scan/sel`.
        var sel: RswiftResources.ImageResource { .init(name: "ble/scan/sel", path: ["ble", "scan"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }
    }

    /// This `_R.image.com` struct is generated, and contains static references to 7 coms, and 3 namespaces.
    struct com {
      let bundle: Foundation.Bundle

      /// Image `com/detail`.
      var detail: RswiftResources.ImageResource { .init(name: "com/detail", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/filter`.
      var filter: RswiftResources.ImageResource { .init(name: "com/filter", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/goto`.
      var goto: RswiftResources.ImageResource { .init(name: "com/goto", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/search`.
      var search: RswiftResources.ImageResource { .init(name: "com/search", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/setting`.
      var setting: RswiftResources.ImageResource { .init(name: "com/setting", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/tip`.
      var tip: RswiftResources.ImageResource { .init(name: "com/tip", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/user`.
      var user: RswiftResources.ImageResource { .init(name: "com/user", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      var rssi: rssi { .init(bundle: bundle) }
      var select: select { .init(bundle: bundle) }
      var sort: sort { .init(bundle: bundle) }

      func rssi(bundle: Foundation.Bundle) -> rssi {
        .init(bundle: bundle)
      }
      func select(bundle: Foundation.Bundle) -> select {
        .init(bundle: bundle)
      }
      func sort(bundle: Foundation.Bundle) -> sort {
        .init(bundle: bundle)
      }


      /// This `_R.image.com.rssi` struct is generated, and contains static references to 6 rssis.
      struct rssi {
        let bundle: Foundation.Bundle

        /// Image `com/rssi/level0`.
        var level0: RswiftResources.ImageResource { .init(name: "com/rssi/level0", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level1`.
        var level1: RswiftResources.ImageResource { .init(name: "com/rssi/level1", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level2`.
        var level2: RswiftResources.ImageResource { .init(name: "com/rssi/level2", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level3`.
        var level3: RswiftResources.ImageResource { .init(name: "com/rssi/level3", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level4`.
        var level4: RswiftResources.ImageResource { .init(name: "com/rssi/level4", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level5`.
        var level5: RswiftResources.ImageResource { .init(name: "com/rssi/level5", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.com.select` struct is generated, and contains static references to 2 selects.
      struct select {
        let bundle: Foundation.Bundle

        /// Image `com/select/nor`.
        var nor: RswiftResources.ImageResource { .init(name: "com/select/nor", path: ["com", "select"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/select/sel`.
        var sel: RswiftResources.ImageResource { .init(name: "com/select/sel", path: ["com", "select"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.com.sort` struct is generated, and contains static references to 2 sorts.
      struct sort {
        let bundle: Foundation.Bundle

        /// Image `com/sort/down`.
        var down: RswiftResources.ImageResource { .init(name: "com/sort/down", path: ["com", "sort"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/sort/up`.
        var up: RswiftResources.ImageResource { .init(name: "com/sort/up", path: ["com", "sort"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }
    }

    /// This `_R.image.doc` struct is generated, and contains static references to 2 docs.
    struct doc {
      let bundle: Foundation.Bundle

      /// Image `doc/file`.
      var file: RswiftResources.ImageResource { .init(name: "doc/file", path: ["doc"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `doc/folder`.
      var folder: RswiftResources.ImageResource { .init(name: "doc/folder", path: ["doc"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }

    /// This `_R.image.hud` struct is generated, and contains static references to 6 huds.
    struct hud {
      let bundle: Foundation.Bundle

      /// Image `hud/ask`.
      var ask: RswiftResources.ImageResource { .init(name: "hud/ask", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `hud/ban`.
      var ban: RswiftResources.ImageResource { .init(name: "hud/ban", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `hud/failure`.
      var failure: RswiftResources.ImageResource { .init(name: "hud/failure", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `hud/info`.
      var info: RswiftResources.ImageResource { .init(name: "hud/info", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `hud/loading`.
      var loading: RswiftResources.ImageResource { .init(name: "hud/loading", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `hud/success`.
      var success: RswiftResources.ImageResource { .init(name: "hud/success", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }

    /// This `_R.image.triangle` struct is generated, and contains static references to 4 triangles.
    struct triangle {
      let bundle: Foundation.Bundle

      /// Image `triangle/bottom`.
      var bottom: RswiftResources.ImageResource { .init(name: "triangle/bottom", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `triangle/left`.
      var left: RswiftResources.ImageResource { .init(name: "triangle/left", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `triangle/right`.
      var right: RswiftResources.ImageResource { .init(name: "triangle/right", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `triangle/top`.
      var top: RswiftResources.ImageResource { .init(name: "triangle/top", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
            var uiSceneStoryboardFile: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneStoryboardFile") ?? "Main" }
          }
        }
      }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}