//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 3 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var launchScreen: launchScreen { .init(source: .init(bundle: bundle, tableName: "LaunchScreen", preferredLanguages: preferredLanguages, locale: locale)) }
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }
    var main: main { .init(source: .init(bundle: bundle, tableName: "Main", preferredLanguages: preferredLanguages, locale: locale)) }

    func launchScreen(preferredLanguages: [String]) -> launchScreen {
      .init(source: .init(bundle: bundle, tableName: "LaunchScreen", preferredLanguages: preferredLanguages, locale: locale))
    }
    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }
    func main(preferredLanguages: [String]) -> main {
      .init(source: .init(bundle: bundle, tableName: "Main", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.launchScreen` struct is generated, and contains static references to 0 localization keys.
    struct launchScreen {
      let source: RswiftResources.StringResource.Source
    }

    /// This `_R.string.localizable` struct is generated, and contains static references to 10 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: BleMessager
      ///
      /// Key: CFBundleDisplayName
      ///
      /// Locales: en, zh-Hans
      var cfBundleDisplayName: RswiftResources.StringResource { .init(key: "CFBundleDisplayName", tableName: "Localizable", source: source, developmentValue: "BleMessager", comment: nil) }

      /// en translation: 请输入设备名称
      ///
      /// Key: central_search_ph
      ///
      /// Locales: en
      var central_search_ph: RswiftResources.StringResource { .init(key: "central_search_ph", tableName: "Localizable", source: source, developmentValue: "请输入设备名称", comment: nil) }

      /// en translation: RSSI
      ///
      /// Key: central_sort_RSSI
      ///
      /// Locales: en
      var central_sort_RSSI: RswiftResources.StringResource { .init(key: "central_sort_RSSI", tableName: "Localizable", source: source, developmentValue: "RSSI", comment: nil) }

      /// en translation: 名称
      ///
      /// Key: central_sort_name
      ///
      /// Locales: en
      var central_sort_name: RswiftResources.StringResource { .init(key: "central_sort_name", tableName: "Localizable", source: source, developmentValue: "名称", comment: nil) }

      /// en translation: 手机作为中央设备来扫描和连接周围的蓝牙外设
      ///
      /// Key: entrance_opt_central_subtitle
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_central_subtitle: RswiftResources.StringResource { .init(key: "entrance_opt_central_subtitle", tableName: "Localizable", source: source, developmentValue: "手机作为中央设备来扫描和连接周围的蓝牙外设", comment: nil) }

      /// en translation: 中心模式
      ///
      /// Key: entrance_opt_central_title
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_central_title: RswiftResources.StringResource { .init(key: "entrance_opt_central_title", tableName: "Localizable", source: source, developmentValue: "中心模式", comment: nil) }

      /// en translation: 手机作为外围设备广播数据
      ///
      /// Key: entrance_opt_peripheral_subtitle
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_peripheral_subtitle: RswiftResources.StringResource { .init(key: "entrance_opt_peripheral_subtitle", tableName: "Localizable", source: source, developmentValue: "手机作为外围设备广播数据", comment: nil) }

      /// en translation: 外设模式
      ///
      /// Key: entrance_opt_peripheral_title
      ///
      /// Locales: en, zh-Hans
      var entrance_opt_peripheral_title: RswiftResources.StringResource { .init(key: "entrance_opt_peripheral_title", tableName: "Localizable", source: source, developmentValue: "外设模式", comment: nil) }

      /// en translation: BleMessager
      ///
      /// Key: name
      ///
      /// Locales: en, zh-Hans
      var name: RswiftResources.StringResource { .init(key: "name", tableName: "Localizable", source: source, developmentValue: "BleMessager", comment: nil) }

      /// en translation: 蓝牙通信，畅享每一刻。
      ///
      /// Key: slogen
      ///
      /// Locales: en, zh-Hans
      var slogen: RswiftResources.StringResource { .init(key: "slogen", tableName: "Localizable", source: source, developmentValue: "蓝牙通信，畅享每一刻。", comment: nil) }
    }

    /// This `_R.string.main` struct is generated, and contains static references to 0 localization keys.
    struct main {
      let source: RswiftResources.StringResource.Source
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 11 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `background`.
    var background: RswiftResources.ColorResource { .init(name: "background", path: [], bundle: bundle) }

    /// Color `black`.
    var black: RswiftResources.ColorResource { .init(name: "black", path: [], bundle: bundle) }

    /// Color `container`.
    var container: RswiftResources.ColorResource { .init(name: "container", path: [], bundle: bundle) }

    /// Color `placeholder`.
    var placeholder: RswiftResources.ColorResource { .init(name: "placeholder", path: [], bundle: bundle) }

    /// Color `primary`.
    var primary: RswiftResources.ColorResource { .init(name: "primary", path: [], bundle: bundle) }

    /// Color `secondary`.
    var secondary: RswiftResources.ColorResource { .init(name: "secondary", path: [], bundle: bundle) }

    /// Color `separator`.
    var separator: RswiftResources.ColorResource { .init(name: "separator", path: [], bundle: bundle) }

    /// Color `subtitle`.
    var subtitle: RswiftResources.ColorResource { .init(name: "subtitle", path: [], bundle: bundle) }

    /// Color `title`.
    var title: RswiftResources.ColorResource { .init(name: "title", path: [], bundle: bundle) }

    /// Color `white`.
    var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 1 images, and 1 namespaces.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `logo`.
    var logo: RswiftResources.ImageResource { .init(name: "logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    var com: com { .init(bundle: bundle) }

    func com(bundle: Foundation.Bundle) -> com {
      .init(bundle: bundle)
    }


    /// This `_R.image.com` struct is generated, and contains static references to 3 coms, and 3 namespaces.
    struct com {
      let bundle: Foundation.Bundle

      /// Image `com/filter`.
      var filter: RswiftResources.ImageResource { .init(name: "com/filter", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/goto`.
      var goto: RswiftResources.ImageResource { .init(name: "com/goto", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `com/search`.
      var search: RswiftResources.ImageResource { .init(name: "com/search", path: ["com"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      var rssi: rssi { .init(bundle: bundle) }
      var select: select { .init(bundle: bundle) }
      var sort: sort { .init(bundle: bundle) }

      func rssi(bundle: Foundation.Bundle) -> rssi {
        .init(bundle: bundle)
      }
      func select(bundle: Foundation.Bundle) -> select {
        .init(bundle: bundle)
      }
      func sort(bundle: Foundation.Bundle) -> sort {
        .init(bundle: bundle)
      }


      /// This `_R.image.com.rssi` struct is generated, and contains static references to 6 rssis.
      struct rssi {
        let bundle: Foundation.Bundle

        /// Image `com/rssi/level0`.
        var level0: RswiftResources.ImageResource { .init(name: "com/rssi/level0", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level1`.
        var level1: RswiftResources.ImageResource { .init(name: "com/rssi/level1", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level2`.
        var level2: RswiftResources.ImageResource { .init(name: "com/rssi/level2", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level3`.
        var level3: RswiftResources.ImageResource { .init(name: "com/rssi/level3", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level4`.
        var level4: RswiftResources.ImageResource { .init(name: "com/rssi/level4", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/rssi/level5`.
        var level5: RswiftResources.ImageResource { .init(name: "com/rssi/level5", path: ["com", "rssi"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.com.select` struct is generated, and contains static references to 2 selects.
      struct select {
        let bundle: Foundation.Bundle

        /// Image `com/select/nor`.
        var nor: RswiftResources.ImageResource { .init(name: "com/select/nor", path: ["com", "select"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/select/sel`.
        var sel: RswiftResources.ImageResource { .init(name: "com/select/sel", path: ["com", "select"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.com.sort` struct is generated, and contains static references to 2 sorts.
      struct sort {
        let bundle: Foundation.Bundle

        /// Image `com/sort/down`.
        var down: RswiftResources.ImageResource { .init(name: "com/sort/down", path: ["com", "sort"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `com/sort/up`.
        var up: RswiftResources.ImageResource { .init(name: "com/sort/up", path: ["com", "sort"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }
    }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
            var uiSceneStoryboardFile: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneStoryboardFile") ?? "Main" }
          }
        }
      }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}